# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Projects"  # Title of the link.
  url = "project/"  # Widget Page folder name.
  weight = 20  # Position of the link in the navigation bar.

[[main]]
  name = "Publications"  # Title of the link.
  url = "publication/"  # Widget Page folder name.
  weight = 30  # Position of the link in the navigation bar.

#[[main]]
#  name = "Posts"  # Title of the link.
#  url = "post/"  # Widget Page folder name.
#  weight = 40  # Position of the link in the navigation bar.

[[main]]
  name = "CV"  # Title of the link.
  url = "files/Anderson_CV_Jul2024.pdf" 
  weight = 50  # Position of the link in the navigation bar.
  

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/resume.pdf"
#    weight = 70
